### ISSUE TITLE
XSRF in rails-api

### ISSUE THREAD

**Issue by smarquez1** [rails-api/rails-api#150]
I am using rails-api with an angularjs application. Since rails-api doesn't include the protect_from_forgery method: Do I still need to configure both applications to protect from CSRF attacks? I think it should be useful to include this sort of information on the readme.

Thanks!

**Comment by gnapse** [comment]
Is there anything wrong with keeping cookie-based auth in the API? Because this phrase in the README seems to suggest it's dumb, but I don't see why?

> You aren't using cookie-based authentication for your API, are you?

**Comment by steveklabnik** [comment]
@gnapse cookies are almost exclusively a browser thing, not an API thing.

You *can* still do it, but I'm not aware of any APIs that do.

**Comment by gnapse** [comment]
The thing is, if you want an SPA to communicate with a backend component securely, a http-only cookie might be the best or only option. Otherwise the SPA will need to store the token somewhere, and presumably there are only a few options to do so (localstorage, session storage, or a cookie used just as a storage mechanism). All those have the problem that if an attacker manages to cross-side-script you (XSS), it will also have access to the token.

**Comment by steveklabnik** [comment]
> All those have the problem that if an attacker manages to cross-side-script you (XSS), it will also have access to the token.

XSS can absolutely grab a cookie too.

**Comment by gnapse** [comment]
I meant httpOnly cookies. The thing is, with token-based auth, single-page apps in the browser have no other means to store the token than in plain sight (local storage, session storage or a normal cookie just used as a storage mechanism), because they need to read it in order to manually include it as a header in every single api request. This makes them vulnerable to what I was mentioning above.

However, if you keep the authentication based on a cookie automatically sent by the browser, and you make this cookie httpOnly, you are no longer vulnerable to a XSS attacker being able to read your token. You have of course to keep protecting yourself from XSS, but in the unfortunate case you become vulnerable to it, your token is not compromised.

My point with all this is, that phrase in the README is intimidating, and I want to know to what degree is justified. It implicitly suggests that using cookie based auth to communicate securely with an api is wrong and shouldn't be done. And I'm trying to understand if it really is wrong and why, because it contradicts other recommendations I've seen elsewhere, all around the issue I've been describing.

**Comment by bmorton** [comment]
You’d have to guard against CSRF then since the browser would be sending that authentication cookie with any request.

**Comment by gnapse** [comment]
Yes. Agreed. But that's beyond the point I'm trying to make here. My point is, is it inherently wrong to use cookie-based authentication when communicating with an api? If so, why? If not, then the phrase is there for no good reason.
