### ISSUE TITLE
Why does this gem need nokogiri?

### ISSUE THREAD

**Issue by thecodethinker** [rails-api/rails-api#186]
When installing this gem I noticed that it also installs nokogiri. In rails, I believe, nokogiri is used to generate the HTML pages so why is it included with this?

It makes using this gem with jruby a little more of a hassle as nokogiri doesn't play nice with jruby be default.

Is there any way we can remove this without breaking anyhing?

**Comment by steveklabnik** [comment]
We depend on rails: https://github.com/rails-api/rails-api/blob/master/rails-api.gemspec#L28-L31

So it gets installed as part of that.

**Comment by thecodethinker** [comment]
Didn't you remove some middleware from rails in order to make this gem?
Can't you do that with nokogiri, or is nokogiri tightly integrated?

**Comment by steveklabnik** [comment]
We use tons of rails internals, like generators, engines, etc. We don't use nokogiri at all. But in order to use those rails internals, we have to depend on rails, and so it gets included as a transitive dependency.

**Comment by rafaelfranca** [comment]
Nokogiri is a hard dependency of action pack to make possible sanitize user
input before rendering. This sanitization method can be used in a html,
JSON, or XML response, so it is not just for html. So this gem should not
really avoid it.

**Comment by thecodethinker** [comment]
I understand. I was just hoping this could be a little piece of fat we cut out.

**Comment by yordis** [comment]
@rafaelfranca because I created this https://github.com/rails/rails/issues/21831 I really want to understand and take the challenge and responsibility to remove that gem if I can. Seriously, it bothers me too much to run little containers with some JSON APIs on top of Rails and wait that long for that gem to install.

Please can you give me some references/advance in the Rails source code about Nokogiri for JSON APIs as well.

**Comment by rafaelfranca** [comment]
Sure! The gem that I'm talking about is https://github.com/rails/rails-html-sanitizer.

It can be used in JSON APIs if the application is sanitizing user input that is HTML to store in the database, to render as value of a JSON response or to do whathever they want wit the sanitized user input.

Here is a simple example of a controller:

```ruby
def show
  render json: { foo: sanitize(params[:omg_html] }
end

def sanitize(html)
  Rails::Html::FullSanitizer.new.sanitize(html)
end
```

Probabily you will easily remove it from Action Pack, but from Action View it is not that easy since it is used for assertions and if you use the `rails` gem, even in the API mode `actionview` will be installed and nokogiri too.

But If what bothers you is nokogiri taking too much to install maybe you should cache your containers (this is what we do at Shopify) or fix the install time of nokogiri.

**Comment by yordis** [comment]
@rafaelfranca The containers are cache but still every time you have to build a new image there is no cache so.

I try to see if I can do something in nokogiri, little I have experience waiting hopefully ~40 seconds for that gem only.
