### ISSUE TITLE
secret_key_base not defined

### ISSUE THREAD

**Issue by ace** [rails-api/rails-api#72]
A new rails4 API app raises an error because secret_key_base is not defined.

I've taken a look at the rails code and it seems that secret_key_base or the deprecated secret_token must be defined (correct me if I'm wrong).

Rails-api doesn't define either of them. I'm not sure if it should for an api-only app.

So, should one of those config values be defined in the app skeleton? Or should rails-api try to ignore them for an api-only app?

**Comment by zirexba** [comment]
Man @kristianmandrup  Thanks a lot !!

**Comment by mecampbellsoup** [comment]
Hey guys - 

So, `rails-api` apps should probably check whether `config.api_only == true` [here](https://github.com/rails/rails/blob/e530534265d2c32b5c5f772e81cb9002dcf5e9cf/railties/lib/rails/application.rb#L513) before attempting to validate the secret key, correct?

As I understand it, since there's no session-related middleware for an API-only app, the secret key base is not used by `rails-api` applications, correct?

cc @steveklabnik @dividedmind @ace 

Thanks 😄

**Comment by MmKolodziej** [comment]
I've just stumbled upon that in latest rails version. I really don't think it's enough to tell users to "define it as whatever", as the first time anybody will face this issue will be upon production deployment.

**Comment by mark-d-holmberg** [comment]
https://gist.github.com/mark-d-holmberg/7df6af48f3b7b16a5db667695853e939

Yeah, it's a bug, and it needs addressed. Here's a gist 6 years later. Sorry for the delay.
